# Generated by Django 2.2 on 2020-04-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
                ('imgUrl', models.URLField(default='https://image.flaticon.com/icons/png/512/18/18436.png')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='api.Category')),
            ],
        ),
    ]
